from __future__ import annotations

from typing import Protocol

from c_hypermem.schema import SharedNode, ViewEdge


class MemoryStore(Protocol):
    def reset_namespace(self, namespace: str) -> None: ...

    def upsert_nodes(self, nodes: list[SharedNode]) -> None: ...

    def upsert_edges(self, edges: list[ViewEdge]) -> None: ...

    def list_nodes(self, namespace: str) -> list[SharedNode]: ...

    def list_edges(self, namespace: str) -> list[ViewEdge]: ...

    def get_nodes(self, namespace: str, node_ids: list[str]) -> list[SharedNode]: ...

    def get_incident_edges(self, namespace: str, node_ids: list[str]) -> list[ViewEdge]: ...

    def stats(self, namespace: str) -> dict[str, int]: ...

    def close(self) -> None: ...

